console.log("TypeScript working ...");
let myString:string;
myString='Strongly typed js';
console.log(myString);
let myNum:number;
myNum=22;
console.log(myNum);
let myBool:boolean;
myBool=true;
console.log(myBool);
let myVar:any;
myVar=5;
console.log(myVar);
myVar='string';
console.log(myVar);
let myStringArray:string[];
myStringArray=['my','your','whose'];
console.log(myStringArray);
let numArray:Array<number>;
numArray=[1,2,3,4,5];
console.log(numArray);
let myTuple:[string,number];
myTuple=['string',1,2,3];
console.log(myTuple);