console.log("TypeScript working ...");
var myString;
myString = 'Strongly typed js';
console.log(myString);
var myNum;
myNum = 22;
console.log(myNum);
var myBool;
myBool = true;
console.log(myBool);
var myVar;
myVar = 5;
console.log(myVar);
myVar = 'string';
console.log(myVar);
var myStringArray;
myStringArray = ['my', 'your', 'whose'];
console.log(myStringArray);
var numArray;
numArray = [1, 2, 3, 4, 5];
console.log(numArray);
var myTuple;
myTuple = ['string', 1, 2, 3];
console.log(myTuple);
